version: '3.8'

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    mem_limit: 6g      # Limit Ollama to 6GB of memory

volumes:
  ollama:
